### ISSUE TITLE
version 4.2 to v4.5 problem

### ISSUE THREAD

**Issue by wmjlxl** [zhuhaow/SpechtLite#10]
Hi,

glad to see that you fixed the config names from the drop list.

but when 'set as system proxy' is selected and i want to exit SpechtLite,  i need to input passwd to confirm again.  

v 4.1 doesnt have such problem, pls kindly check and fix it.

thanks

**Comment by wmjlxl** [comment]
also my osx freeze randomly, not sure whether it was caused by v4.2-4.5 or not.

i am rollback to v4.1 seems normal now.

**Comment by zhuhaow** [comment]
I do not see any of the problems on my side, which version of macOS are you on?

**Comment by wmjlxl** [comment]
macOS Sierra v10.12(16A323)

now i am using v4.1 and no such issue.
so i can cfm it was caused by v4.2-4.5 version.

**Comment by zhuhaow** [comment]
What's the output of `ls -la /Library/Application\ Support/SpechtLite/`

**Comment by wmjlxl** [comment]
ls -la /Library/Application\ Support/SpechtLite/
total 7024
drwxr-xr-x   3 root  admin      102 Sep 23 23:00 .
drwxr-xr-x  32 root  admin     1088 Sep 23 23:00 ..
-rwsr-sr-x@  1 root  admin  3595880 Sep 24 14:49 ProxyConfig


fyi
