### ISSUE TITLE
设置log记录粒度

### ISSUE THREAD

**Issue by yichengchen** [zhuhaow/SpechtLite#11]
注意到目前log记录了所有的request，是否可以设置log记录级别呢？

**Comment by zhuhaow** [comment]
你是觉得log太多还是太少

Zhuhao Wang

2016年9月24日 +0800 16:23 陈奕程 <notifications@github.com>，写道：

**Comment by yichengchen** [comment]
我觉得目前对普通用户log太多了…感觉不需要记录全部的请求，只有在调试规则时需要目前这种情况。

发自我的 iPhone

**Comment by zhuhaow** [comment]
你不看不就好了

Zhuhao Wang

2016年9月24日 +0800 16:28 陈奕程 <notifications@github.com>，写道：

**Comment by gonejack** [comment]
我觉得log太少，死妈的Mac Mail.app 连接 Gmail 的 smtp.gmail.com 这个服务器无限菊花，但 imap.gmail.com 又没问题，想查具体原因。

**Comment by zhuhaow** [comment]
很多服务器会屏蔽连接到25端口来防止发放垃圾邮件，你可以登上服务器试试能不能连smtp的25，应该是被禁了。
