### ISSUE TITLE
请问有支持SSR的计划吗？

### ISSUE THREAD

**Issue by Vxider** [zhuhaow/SpechtLite#13]
目前我这边网络环境下SS不太好用，SSR则没有问题，请问有支持SSR的计划吗？

**Comment by zhuhaow** [comment]
低优先级，慢慢等

Best regards,
Zhuhao Wang

2016年10月3日 +0800 20:50 Vxider <notifications@github.com>，写道：

**Comment by zhuhaow** [comment]
低优先级，慢慢等
