### ISSUE TITLE
配置文件是否支持 Shadowsocks One Time Auth 呢？

### ISSUE THREAD

**Issue by arfaWong** [zhuhaow/SpechtLite#14]
Shadowsocks One Time Auth 的说明在下面这个链接里。
https://shadowsocks.org/en/spec/one-time-auth.html

在 Shadowsocks windows 版本中，开启这个功能，只要设置 "auth": true 即可。

**Comment by zhuhaow** [comment]
暂不

**Comment by arfaWong** [comment]
了解了，谢谢！
