### ISSUE TITLE
npm install SpechtLite会崩溃

### ISSUE THREAD

**Issue by jiangyinjie** [zhuhaow/SpechtLite#17]

**Comment by jiangyinjie** [comment]
npm install 的时候，SpechtLite没有响应，在Activity Monitor看是not Response

**Comment by zhuhaow** [comment]
和npm没有啥关系，curl呢？
这个bug在网络极不稳定或者不能访问外网的时候可能会有，原因不明。

**Comment by zhuhaow** [comment]
和npm没有啥关系，curl呢？
这个bug在网络极不稳定或者不能访问外网的时候可能会有，原因不明。

**Comment by lampchop** [comment]
我是用的你的release 的app， 也存在崩溃问题， 目前不能重启了， 关机重启电脑后还是不能启动spechtlite，不知道怎么才能启动。 menu 栏里也没有这个app显示了

**Comment by zhuhaow** [comment]
crash log给我看一下。去系统设置里面把代理去掉就可以正常上网了
