### ISSUE TITLE
请问是否还没支持OTA功能？

### ISSUE THREAD

**Issue by scymen** [zhuhaow/SpechtLite#18]
请问是否还没支持OTA功能？我找了很久没有找到在哪里设置，还是说我姿势不对？
thanks

**Comment by zhuhaow** [comment]
不支持

-------------------
Zhuhao Wang
Zhejiang university

2016年10月19日 +0800 09:50 Scythe Men <notifications@github.com>，写道：

**Comment by zhuhaow** [comment]
不支持
