### ISSUE TITLE
随系统启动有事会弹出错误信息

### ISSUE THREAD

**Issue by Boms** [zhuhaow/SpechtLite#20]
![2016-11-02 09 18 59](https://cloud.githubusercontent.com/assets/1822395/19913574/d5f3665e-a0de-11e6-8893-1ef5f6823f1f.png)

随系统启动经常会以上错误信息，app版本0.4.9(136)，系统版本10.11.6
关闭app，重新打开还会有同样的错误信息弹出，需要重启后正常（有时要重启多次）。

**Comment by zhuhaow** [comment]
因为你有其他程序占用了端口
重启就是让大家重新抢一次

2016年11月2日 +0800 09:32 Boms <notifications@github.com>，写道：
