### ISSUE TITLE
取消代理后端口和系统忽略代理设置未清空以及切换配置后端口问题

### ISSUE THREAD

**Issue by waitusz** [zhuhaow/SpechtLite#24]
建议在取消代理设置后将系统的代理端口以及忽略代理设置里的内容清空，目前的版本在取消代理后端口被设置为0，忽略代理设置的内容未进行清空处理。
另外设置代理后在切换配置文件后端口也未能根据配置文件中的端口进行重新设置

**Comment by zhuhaow** [comment]
Fixed
