### ISSUE TITLE
0.5.1版本问题

### ISSUE THREAD

**Issue by waitusz** [zhuhaow/SpechtLite#25]
1、在0.5.1版本中show log失效
2、同样的规则配置文件部分规则在0.4.9中能正确响应处理，但在0.5.1中不能正确访问

**Comment by zhuhaow** [comment]
1. 我这里测试的没问题
2. 规则贴一下

**Comment by googya** [comment]
我这样配置会有问题么？

![snip20161122_2](https://cloud.githubusercontent.com/assets/118465/20519948/f61599a0-b0df-11e6-8780-f1b4288febfd.png)



![snip20161122_4](https://cloud.githubusercontent.com/assets/118465/20519987/132ce5e8-b0e0-11e6-8a9a-1fea57eb2071.png)

**Comment by zhuhaow** [comment]
https://github.com/zhuhaow/SpechtLite/wiki/如何配置Specht-Lite
还不会的话去群里问

**Comment by googya** [comment]
👍

**Comment by waitusz** [comment]
我将我最近整理制作的完整规则上传到了https://github.com/waitusz/Rules-store/tree/master/SpechtLite
今天重新更新新版后问题没有了，show log调用也可以了，规则也正常了
我在proxylist文件中添加了\brapidgator关键字规则（用来在macbed下载的时候选择rapidgator网盘下载使用代理），昨天更新新版后下载显示连接中断，想看日志竟然怎么都调用不出来，改回0.4.9后问题解决，我后来重新更新到新版问题又出现了，就重新转会0.4.9，今天看到你回复再次更新新版，竟然没有再出现问题，不知道是不是我系统的问题，还是间歇性抽风的问题。

**Comment by googya** [comment]
@waitusz 按照你的配置， 已经运行起来了！🙏
