### ISSUE TITLE
0.6.0beta10导致网络偏好设置中点击代理标签崩溃

### ISSUE THREAD

**Issue by waitusz** [zhuhaow/SpechtLite#26]
无意中发现最新版0.6.0beta10在设置代理后，进入网络偏好-高级后点击代理标签会导致崩溃，即便是再取消代理，甚至退出spechtlite也是一样，这时候如果用其他ss客户端启用一下代理后就会回复正常
不知道是通病还是个例
<img width="510" alt="jt" src="https://cloud.githubusercontent.com/assets/22133928/20615996/af170fde-b319-11e6-8b80-cd9fa8b22daf.png">

**Comment by zhuhaow** [comment]
无法重现

**Comment by waitusz** [comment]
@zhuhaow 你那边正常？我卸载后重启电脑，再重新安装后问题依旧

**Comment by zhuhaow** [comment]
正常，群里问吧

**Comment by waitusz** [comment]
@zhuhaow 哪个群？经过完全卸载后重新安装0.4.9和0.6.0beta比较基本可以认为是安装的ProxyConfig的问题，完全重新安装0.4.9正常，之后在这个基础上升级到0.6.0也没有问题，但如果卸载干净后全新完全安装0.6.0就会出现我的网络偏好崩溃问题

**Comment by zhuhaow** [comment]
明白了，swift3还没测过。

**Comment by zhuhaow** [comment]
Fixed
