### ISSUE TITLE
spechtlite会自动选择速度最快的代理吗？

### ISSUE THREAD

**Issue by herozhang** [zhuhaow/SpechtLite#28]
我这里有19个代理的配置，
spechtlite目前是什么逻辑去选择的呢？
是否有办法手动控制所选择的代理

**Comment by ChengLuffy** [comment]
看到了说一句。
`SpechtLite` 的 **speed** 规则或自动选择相应最快的节点，这个没问题，然后如果节点都在一个 **yaml** 文件里目前是没有办法使用图形界面选择其中的单个代理的。
可用的操作时，打开相应的 **yaml** 文件在 **speed** 下对不想用的节点用 `#` 注释掉，保存，然后 `reload config`
另外一个 **yaml** 文件下的 `speed` 里放 19 个还是有点夸张的，可以根据节点 **质量** 或者 **地区** 分类创建多个 **yaml** 文件，同时根据质量或者其他优先级设置合理的 `delay`。
