### ISSUE TITLE
speed test 结果普遍上 1700 多。

### ISSUE THREAD

**Issue by DrayChou** [zhuhaow/SpechtLite#29]
总觉得我的ss速度没那么慢吧，为什么都这么大呢？
还是说取的所有ss的平均值？不太懂啊

**Comment by zhuhaow** [comment]
你要是觉得不慢就不要在意，如果在意就在内心把它除100

**Comment by DrayChou** [comment]
呃，你这回答，让我怎么说呢。

我再研究下你的规则吧，目前弄的不是太明白，经常发现页面打不开。

zhuhaow <notifications@github.com> 於 2016年12月8日 週四 上午11:05寫道：

**Comment by zhuhaow** [comment]
打不开是规则问题，速度测试测试的是访问 https://www.google.com/generate_204 的时间
你设想的有意义的速度测试是不存在的
