### ISSUE TITLE
切换配置项的时候，port 并不会切换。

### ISSUE THREAD

**Issue by DrayChou** [zhuhaow/SpechtLite#30]
我有2个配置文件，里面端口号不一样，从 a 配置文件切换到 b 配置文件的时候，系统配置里的端口号并不会变为 b 里配置的端口号，导致切换过来之后所有网站都无法登录，以为系统配置里的代理地址的端口号并没有切过来。

**Comment by zhuhaow** [comment]
诶……一般都不会换端口……谢谢提醒
已修复

**Comment by DrayChou** [comment]
感谢你开发这么好用的app。
zhuhaow <notifications@github.com>於 2016年12月8日 週四，19:13寫道：
