### ISSUE TITLE
0.7.1版本OSX Mail无法发送icloud、gmail邮件

### ISSUE THREAD

**Issue by Bismarrck** [zhuhaow/SpechtLite#32]
OSX 10.12.1

SpechtLite-0.6.0一切正常，但是0.7.1只能接收邮件，不能发送icloud、gmail邮件，我另一个学校邮箱一切正常，既可以发送也可以接收。

<img width="842" alt="screen shot 2016-12-09 at 9 12 51 am" src="https://cloud.githubusercontent.com/assets/719050/21034141/64a36c36-bdf0-11e6-957b-a0e316427391.png">

```
CONNECTED` Dec 09 09:24:29.732 [kCFStreamSocketSecurityLevelNone] -- host:smtp.gmail.com -- port:587 -- socket:0x6100006bfec0 -- thread:0x600001a79900

READ Dec 09 09:24:31.326 [kCFStreamSocketSecurityLevelNone] -- host:smtp.gmail.com -- port:587 -- socket:0x6100006bfec0 -- thread:0x600001a79900
220 smtp.gmail.com ESMTP x2sm52698975pfx.65 - gsmtp

WROTE Dec 09 09:24:31.333 [kCFStreamSocketSecurityLevelNone] -- host:smtp.gmail.com -- port:587 -- socket:0x6100006bfec0 -- thread:0x600001a79900
EHLO [127.0.0.1]
```

**Comment by zhuhaow** [comment]
我这里试了一下没什么问题……你可以看看log里面的请求怎么走的

**Comment by Bismarrck** [comment]
@zhuhaow 我上面贴出来的就是log了，我把gmail的smtp log作为附件传上来。

时间戳Dec 09 09:24:31.333（120行）前后我在测试spechtlite-0.7.1

我测试的时候是直接替换spechtlite程序文件，系统环境、spechtlite的配置文件都没做任何更改

[smtp.gmail.com-2CDE0F66-1029-4335-8A79-A6602A35CA50.txt](https://github.com/zhuhaow/SpechtLite/files/641056/smtp.gmail.com-2CDE0F66-1029-4335-8A79-A6602A35CA50.txt)

**Comment by Bismarrck** [comment]
我现在已经换回0.6.0了，一切正常，刚刚才发了两封icloud邮件

**Comment by zhuhaow** [comment]
我已经可以重现了，我看看，感觉连通了啊

**Comment by zhuhaow** [comment]
Fixed
