### ISSUE TITLE
关于 Adapters SPEED 自动选择?

### ISSUE THREAD

**Issue by Sooongz** [zhuhaow/SpechtLite#37]
Adapters SPEED 自动选择后 能否在 GUI 上体现所选 adapter？

**Comment by zhuhaow** [comment]
每一个请求的adapter可能都不一样

2016年12月26日 +0800 17:54 Bigpo <notifications@github.com>，写道：

**Comment by Sooongz** [comment]
每个请求都会去测试最优线路（理论上）？
还是一段时间测试选取最优线路？

**Comment by zhuhaow** [comment]
每个请求都测

2016年12月26日 +0800 18:40 Bigpo <notifications@github.com>，写道：

**Comment by Sooongz** [comment]
这样 adapter 多的情况 是不是 每次都很慢？
 加入了十几个 adapters 感觉每次一个新的请求 会花费很久

**Comment by ChengLuffy** [comment]
多线程并发测速，采用最先响应的，不是一个一个测速，也不是要等所有的测速都完成。
