### ISSUE TITLE
can not proxy

### ISSUE THREAD

**Issue by nie11kun** [zhuhaow/SpechtLite#4]
i had already add the port in system preference and running the app correctly.
here is my configure.yaml file:
>port: 9090
adapter:
  - id: alpharacks
    type: ss
    host: xxx.xxx.xxx.xxx
    port: xxxx
    method: chacha20
    password: xxxxxxxxxxx
  - id: speed
    type: SPEED
    adapters:
      - id: alpharacks
        delay: 300
      - id: direct
        delay: 0
rule:
  - type: country
    country: CN
    match: true
    adapter: direct
  - type: country
    country: --
    match: true
    adapter: direct
  - type: list
    file: ~/.SpechtLite/directlist
    adapter: direct
  - type: list
    file: ~/.SpechtLite/proxylist
    adapter: alpharacks
  - type: DNSFail
    adapter: speed
  - type: all
    adapter: speed

here is proxy list, just test to add one line:
>google\.com

**Comment by zhuhaow** [comment]
Use [gitter](https://gitter.im/zhuhaow/NEKit?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to discuss this plz.

**Comment by zhuhaow** [comment]
And you should write
```
google\.com
```

**Comment by nie11kun** [comment]
> And you should write

yes i do, but paste here just be "fixed" by markdown
