### ISSUE TITLE
mac下每隔一段时间会卡一下 不能打开网页 过半分钟左右又好了 这是为啥

### ISSUE THREAD

**Issue by sukeyisme** [zhuhaow/SpechtLite#40]

**Comment by zhuhaow** [comment]
因为你的服务器不稳定

2016年12月31日 +0800 16:43 hodge <notifications@github.com>，写道：

**Comment by lioliy** [comment]
服务器不稳定吧，我用这一点也没问题

**Comment by sukeyisme** [comment]
不会吧 我之前用的软件翻墙不会出现这种情况啊 比如surge和meow 一般sleep后在打开 就出现这种情况了

**Comment by sukeyisme** [comment]
问下 这个delay是毫秒吗

**Comment by zhuhaow** [comment]
是，不要用reject，safari有bug

2016年12月31日 +0800 18:52 hodge <notifications@github.com>，写道：

**Comment by sukeyisme** [comment]
一直用chrome 有没有配置文件参考下 我是按readme里配置的

**Comment by sukeyisme** [comment]
有没有可能用了reject 和 adblock plus 插件冲突了

**Comment by zhuhaow** [comment]
不太可能

2016年12月31日 +0800 19:36 hodge <notifications@github.com>，写道：
