### ISSUE TITLE
这样怎么处理

### ISSUE THREAD

**Issue by CoderJin** [zhuhaow/SpechtLite#5]
port: 9090
adapter:
  - id: adapter3        
    type: ss     
    host: xx.x.xx.xx      
    port: 8888        
    method: AES-256-CFB       
    password: 1234     
  - id: speed     
    type: SPEED    
    adapters:    
      - id: adapter3     
        delay: 300      
      - id: direct       
        delay: 0        
rule:      
  - type: country        
    country: CN        
    match: true       
    adapter: direct      
  - type: country       
    country: --      
    match: true        
    adapter: direct        
  - type: list        
    file: ~/.SpechtLite/directlist       
    adapter: direct       
  - type: DNSFail       
    adapter: speed       
  - type: all          
    adapter: speed       
![fd084ab2-48b9-45cf-943d-61194ed2d888](https://cloud.githubusercontent.com/assets/18577384/17866001/75dd92b0-68d7-11e6-8ac3-dbef62e2ae96.png)

这个配置正确不

总是提示这样的错误
![ddb2a4df-0c9d-4a00-b4cf-fac996b1f971](https://cloud.githubusercontent.com/assets/18577384/17865849/c4e9933c-68d6-11e6-8d16-b47858eb86b7.png)
![b56f3e19-1ffa-4edf-8001-1a0e4161481e](https://cloud.githubusercontent.com/assets/18577384/17865856/cc008d42-68d6-11e6-84a1-b9db6d0a9b14.png)

新增了一个文件夹 directlist  提示 没有权限

**Comment by zhuhaow** [comment]
既然不用list那么把相关的rule删掉啊，directlist这个文件都不存在

-------------------
Zhuhao Wang
Zhejiang university

2016年8月23日 +0800 02:11 CoderJin <notifications@github.com>，写道：
