### ISSUE TITLE
Firefox 出现404错误，其他浏览器则不会。

### ISSUE THREAD

**Issue by cnzgray** [zhuhaow/SpechtLite#50]
首先感谢作者开发这么好的一个工具。
但是最近在使用的过程中发现一个问题，chrome代理使用系统配置，Firefox也是同样的设置。
结果Firefox中多点击一两个网页后county为cn的网页后就出现404错误。
Firefox的配置如下：
![image](https://cloud.githubusercontent.com/assets/5411281/24533375/e12ead4a-15f9-11e7-8717-357e71a52867.png)
spechtlite的配置如下：
![image](https://cloud.githubusercontent.com/assets/5411281/24533388/fec74204-15f9-11e7-9e6d-68621f9a2372.png)
经过测试发现，如果全部走代理则不会出现类似问题。

**Comment by cnzgray** [comment]
Firefox的错误页面如下：
![image](https://cloud.githubusercontent.com/assets/5411281/24533422/32dd615e-15fa-11e7-9320-bddaba6c8797.png)

**Comment by zhuhaow** [comment]
设置Firefox走socks5代理

**Comment by cnzgray** [comment]
感谢，暂时测试了下没发现这个问题。比较奇怪的是之前也像这样设置过，但是还是出了一样的问题。我再观察看，如果有问题再进行反馈。
