### ISSUE TITLE
How does rule `type: country` work?

### ISSUE THREAD

**Issue by riobard** [zhuhaow/SpechtLite#56]
Does SpechtLite have embedded IP range database from e.g. MaxMind? If so, how often does it update the database to keep up with the IP allocation changes? Thanks!

**Comment by zhuhaow** [comment]
Almost never.....

The database is provided by the `lexrus/MMDB-Swift`.

**Comment by riobard** [comment]
So is it better to use iplist rule with manually updated IP file from APNIC rather than country rule?

**Comment by zhuhaow** [comment]
I think IP database from MaxMind is far more accurate than APNIC. APNIC just provides how these IPs are allocated, but it does not mean these IP will be used based on the owner's nationality.

**Comment by riobard** [comment]
But isn't GFW more concerned about owners' nationality rather than geolocation? 

Correct me if I'm wrong, I thought MaxMind database is more concerned about geolocation. And you said you almost never update the database…

Sorry this isn't nitpicking. I'm trying to figure out the logic behind the rule design :)

**Comment by zhuhaow** [comment]
First, I don't think GFW bans IP based on location. It doesn't have to. GFW observes all traffic goes overseas, so it does not even have to know the IP location. And it would be too much simpler, but much more damaging if it wants to do that. But it still works in blacklist mode as of now and I don't foresee it to change.

Isn't real geolocation of IP what we are interested in?

As the IPv4 already has run out, relocation is happening and will happen widely. I don't consider the allocation table provided by APNIC very useful.

And the database should be updated more often I think.

**Comment by riobard** [comment]
> First, I don't think GFW bans IP based on location. It doesn't have to. GFW observes all traffic goes overseas, so it does not even have to know the IP location.

Exactly! That’s precisely my point. If GFW does not care about geolocation, it is better to use APNIC data because it reflects network topology and ownership more accurately. 

> Isn't real geolocation of IP what we are interested in?

If GFW does not care about geolocation, why should we? I’m confused.

**Comment by zhuhaow** [comment]
This rule is provided to simplify the setting, i.e., redirect all traffic not in some location to proxy. This is generally what people wants, they want to know where the host is. The location of the owner of the IP is useless. It means nothing, does not indicate anything about where the host is, or how the traffic will be routed.

Neither `NEKit` nor `SpechtLite` ever talks about GFW or is designed specifically for GFW. 
But still, GFW only bans IP overseas, so it makes sense to route everything not in China to a proxy thus it is guaranteed nothing is blocked without the hassle of maintaining a non-exhausted list such as GFWList.

**Comment by riobard** [comment]
If I understand you correctly, you think that a) MaxMind's database gives actual geolocation of IP ranges, and b) APNIC database only says which country the owners of those IP ranges reside in.

Consider an example: an IP range allocated to China Telecom but physically deployed in the US. In this case, APNIC database would say the IP range is in China but MaxMind would report it in the US. Therefore it's better to use MaxMind's data. Correct?

**Comment by zhuhaow** [comment]
Yes

**Comment by riobard** [comment]
Thanks! I now understand the logic behind the choices. Please remember to update the embedded MaxMind database more frequently :) Is it possible for users to manually update it? I think it’s just a single SQLite db file.

**Comment by zhuhaow** [comment]
It is not a SQLite db, as far as I understand.
It will be updated with every new version now.
