### ISSUE TITLE
0.10.5好像不能正常工作

### ISSUE THREAD

**Issue by ericyyyy** [zhuhaow/SpechtLite#57]
Hi zhuhaowang！
晚上使用软件的时候提示有新版本，直接点update不能正常更新，然后特地来github里面下载，移除原来的程序包以后使用心得程序包运行以后不能正常上Facebook，配置使用的是之前的配置。youtube能打开，但是无法播放视频（不确定这个情况是不是本次引起的）但是其他网站打不开，包括proxylist里面手动写入 facebook.com 和google.com 也不能正常打开网站，然后测试 输入 IP138.com， reload以后  IP138网站还是现实宽带的ip.
请您看看是否存在啥问题。

感谢您开发的软件对我们的帮助巨大。

**Comment by zhuhaow** [comment]
就是因为有问题才不让你们更新的。

**Comment by ericyyyy** [comment]
啊，没看到不让更新的提示，哈哈。我还特地以为你在线更新有问题才跑这里来更新。。。现在切换回0.10.4了，谢谢您回复。

**Comment by ericyyyy** [comment]
请问有没有打算新增一个一键全局的功能，有时候某些小网站临时打不开还要特地去写一个地址有点小题大做。

**Comment by zhuhaow** [comment]
写个全局的配置文件切过去就好了

**Comment by ericyyyy** [comment]
嗯嗯 我也刚想到这个办法，谢谢。

**Comment by ericyyyy** [comment]
Zhihaow，您好，有个额外的请教，请问类似带规则的代理软件（支持shttp服务器）的在windows环境下，您知道有什么软件可以做到吗？我只知道shadowsocks可以做，但是它不支持shttp。其他的软件基本都是全局

**Comment by zhuhaow** [comment]
不知道
