### ISSUE TITLE
Crash in Mac 10.12.5

### ISSUE THREAD

**Issue by Chossing** [zhuhaow/SpechtLite#64]
After I reconfig the profile, the program just crashes. Any ideas or any way to see the log?

**Comment by zhuhaow** [comment]
Try to remove all the rules and adapters and add them back one by one

**Comment by Chossing** [comment]
Where can I see the log? The "show log" button does not respond.

**Comment by zhuhaow** [comment]
It should open the console. See if it is in the background.
