### ISSUE TITLE
看看是什么问题

### ISSUE THREAD

**Issue by charleyzhu** [zhuhaow/SpechtLite#66]
在启用代理以后不配置任何规则这个地址也不能打开，在log用也没有任何记录?也不知道是不是跨站和防盗链的问题，这个图片地址是在简书的首页文章列表的右边的配图
http://upload-images.jianshu.io/upload_images/5763525-edc235541b60a96a.png?imageMogr2/auto-orient/strip|imageView2/1/w/300/h/240

**Comment by zhuhaow** [comment]
我这里没问题

**Comment by charleyzhu** [comment]
好的，谢谢，我自己找找问题，目前就只是简书登录后的发现我这不正常其他都非常好，谢谢

**Comment by charleyzhu** [comment]
配置下可以了，配置简书的地址和图片的地址从同一个出口出就正常了，感谢
