### ISSUE TITLE
support to ShadowSocks new encryption error

### ISSUE THREAD

**Issue by huhanghao** [zhuhaow/SpechtLite#71]
ShadowSocks has been changed its encryption method to chacha20-ietf-poly1305. But it seem that SpechtLite did not suppot the new  encryption method.

**Comment by freedomlang** [comment]
Is there a plan to support the encryption mention above ?

**Comment by kingname** [comment]
the same question. according to the document, NEKit can not support chacha20-ietf-poly1305 now, will you add this encryption of will we add it by ourselves?

**Comment by zhuhaow** [comment]
> Will there be support for new protocols in NEKit?

No.

> Will there be support for new protocols in libnekit?

libnekit will only support RFC protocol. Anything other than that (even many are supported already, such as chacha20-ietf-poly1305) will be not be added and existing ones will be removed in the future version. 
libnekit will be redesigned to be easily for anyone (of course with a little understanding of CS) to extend to support any protocol one likes. But I'm not going to maintain anything other than standards.
