### ISSUE TITLE
建议list列表增加Suffix和Keyword支持

### ISSUE THREAD

**Issue by Vxider** [zhuhaow/SpechtLite#72]
目前list里无法区别是domain-suffix还是keyword，例如写入`ad.com`，可能会屏蔽掉`cad.com`，建议增加此项支持

**Comment by ChengLuffy** [comment]
规则以正则进行匹配，学习使用正则匹配即可达到你说的效果

**Comment by Vxider** [comment]
抱歉，没有注意到正则表达式支持，问题现已解决，谢谢！
