### ISSUE TITLE
Hope to support auto configuration choosen based on network SSID

### ISSUE THREAD

**Issue by Vxider** [zhuhaow/SpechtLite#74]
I have multi config files using ipv4 proxy, ipv6 proxy(accelerate download speed) or direct proxy(some network dose not need proxy). I Hope SpechtLite can switch configuration files based on network type or SSID, so it can automatic switch config when my laptop connect different network env automatically.

**Comment by zhuhaow** [comment]
I don't think I would do that since that would make the configuration file to complicated to go.
