### ISSUE TITLE
请问有没有支持SPDY和HTTP2代理的打算？

### ISSUE THREAD

**Issue by wfwdex** [zhuhaow/SpechtLite#8]
如题

**Comment by zhuhaow** [comment]
没有，没有什么意义啊，你能解释一下么，除了http请求以外所有的其它请求都不会被加速，而这年头基本都是https请求
而且还要程序支持，我也不知道iOS和Mac OS支不支持http2 proxy

**Comment by wfwdex** [comment]
哦，那确实没办法了。
