### ISSUE TITLE
Block a specific apps connection?

### ISSUE THREAD

**Issue by umlearn** [zhuhaow/SpechtLite#89]
Is any possible to block a specific apps connection?

**Comment by zhuhaow** [comment]
Not likely to be possible in near future. That feature may be available if I ever got to finish Specht 2

**Comment by umlearn** [comment]
> Not likely to be possible in near future. That feature may be available if I ever got to finish Specht 2

Thanks for the quick reply. I'm a UI/UX designer, it would be nice that can do sth to help with Specht 2.

**Comment by zhuhaow** [comment]
Thank you. I’ll definitely reach out to you when I start specht2

On 20 Dec 2018, at 16:54, UMLEARN <notifications@github.com> wrote:

Not likely to be possible in near future. That feature may be available if I ever got to finish Specht 2

Thanks for the quick reply. I'm a UI/UX designer, it would be nice that can do sth to help with Specht 2.
