### ISSUE TITLE
在retina屏幕上图标看起来似乎还是有些模糊，能否改进下，谢谢

### ISSUE THREAD

**Issue by leewi9** [zhuhaow/SpechtLite#9]
![image](https://cloud.githubusercontent.com/assets/10832544/18612614/41ba7c22-7d91-11e6-91d7-4e09c1aa3f39.png)

![image](https://cloud.githubusercontent.com/assets/10832544/18612606/280d77ac-7d91-11e6-84e2-e01d123438fb.png)

**Comment by zhuhaow** [comment]
没有感觉到什么模糊，而且你截的图也不是retina的分辨率
