### ISSUE TITLE
最新系统无法代理 ‘正在等待代理隧道响应’

### ISSUE THREAD

**Issue by Sky891028** [zhuhaow/SpechtLite#91]
在最新的系统Mac OS 10.14.5 (18F132)
代理不生效

**Comment by zhuhaow** [comment]
如何重现？

**Comment by Sky891028** [comment]
NEkit版本0.12.7 
我看到是在启动代理的这里有异常抛出

        RuleManager.currentManager = configuration.ruleManager

**Comment by zhuhaow** [comment]
我用了很久了都没有任何问题。错误看起来是你这里的ruleManager是空的。

**Comment by Sky891028** [comment]
问题已解决 
是域名的问题 。
谢谢！
